export default {
  data () {
    return {
      frameList: [{
        label: 'React',
        logo: require('./images/react.png'),
        link: '/articleList/Javascript_React',
        bgColor: 'black'
      }, {
        label: 'Vue',
        logo: require('./images/vue.png'),
        link: '/articleList/Javascript_Vue',
        bgColor: 'grey'
      }, {
        label: 'Angular',
        logo: require('./images/angular.png'),
        link: '/articleList/Javascript_Angular',
        bgColor: 'black'
      }, {
        label: 'JQuery',
        logo: require('./images/jquery.png'),
        link: '/articleList/Javascript_JQuery',
        bgColor: 'blue'
      }, {
        label: 'Backbone',
        logo: require('./images/backbone.png'),
        link: '/articleList/Javascript_Backbone',
        bgColor: 'yellow'
      }, {
        label: 'Bootstrip',
        logo: require('./images/bootstrap.png'),
        link: '/articleList/Javascript_Bootstrip',
        bgColor: 'violet'
      }, {
        label: 'Express',
        logo: require('./images/express.png'),
        link: '/articleList/Javascript_Express',
        bgColor: 'red'
      }],
      toolList: [{
        label: 'Webpack',
        logo: require('./images/webpack.png'),
        link: '/articleList/Tool_Webpack',
        bgColor: 'grey'
      }, {
        label: 'Gulp',
        logo: require('./images/gulp.png'),
        link: '/articleList/Tool_Gulp',
        bgColor: 'red'
      }, {
        label: 'Github',
        logo: require('./images/github.jpg'),
        link: '/articleList/Tool_Github',
        bgColor: 'white'
      }, {
        label: 'Chrome',
        logo: require('./images/chrome.png'),
        link: '/articleList/Tool_Chrome',
        bgColor: 'black'
      }, {
        label: 'Dede',
        logo: require('./images/dede.png'),
        link: '/articleList/Tool_Dede',
        bgColor: 'green'
      }, {
        label: 'Editor',
        logo: require('./images/editor.png'),
        link: '/articleList/Tool_Editor',
        bgColor: 'violet'
      }, {
        label: 'Others',
        logo: require('./images/others.png'),
        link: '/articleList/Tool_Others',
        bgColor: 'black'
      }],
      bookList: [{
        label: '高级程序设计',
        link: '/articleList/Book_Gjcxsj',
        logo: require('./images/gjcxsj.jpg')
      }, {
        label: '设计模式',
        link: '/articleList/Book_Sjms',
        logo: require('./images/sjms.jpg')
      }, {
        label: 'Es6入门',
        link: '/articleList/Book_Es6rm',
        logo: require('./images/es6.jpg')
      }, {
        label: '函数式编程',
        link: '/articleList/Book_Hssbc',
        logo: require('./images/hssbc.jpg')
      }],
      otherList: [{
        label: 'Game',
        link: '/articleList/Others_Game',
        logo: require('./images/game.png'),
        bgColor: 'black'
      }, {
        label: 'Canvas',
        link: '/articleList/Others_Canvas',
        logo: require('./images/canvas.png'),
        bgColor: 'white'
      }, {
        label: 'Design',
        link: '/articleList/Others_Design',
        logo: require('./images/design.png'),
        bgColor: 'green'
      }, {
        label: 'PlugIn',
        link: '/articleList/Others_PlugIn',
        logo: require('./images/plugin.png'),
        bgColor: 'black'
      }, {
        label: 'Template',
        link: '/articleList/Others_Template',
        logo: require('./images/template.png'),
        bgColor: 'yellow'
      }, {
        label: 'Collection',
        link: '/articleList/User_Collection',
        logo: require('./images/collection.png'),
        bgColor: 'white'
      }, {
        label: 'Message',
        link: '/message',
        logo: require('./images/message.png'),
        bgColor: 'red'
      }]
    }
  }
}
