export default {
  data () {
    return {
      langList: [{
        title: 'javascript',
        link: '/articleList/fronts_javascript'
      }, {
        title: 'es6',
        link: '/articleList/fronts_es6'
      }, {
        title: 'html',
        link: '/articleList/fronts_html'
      }, {
        title: 'css',
        link: '/articleList/fronts_css'
      }, {
        title: 'nodeJs',
        link: '/articleList/backstages_node'
      }, {
        title: 'vue',
        link: '/articleList/fronts_vue'
      }, {
        title: 'react',
        link: '/articleList/fronts_react'
      }, {
        title: 'jquery',
        link: '/articleList/fronts_jquery'
      }, {
        title: 'java',
        link: '/articleList/backstages_java'
      }, {
        title: 'koa',
        link: '/articleList/backstages_koa'
      }, {
        title: 'mysql',
        link: '/articleList/backstages_mysql'
      }, {
        title: 'bootstrip',
        link: '/articleList/fronts_bootstrip'
      }, {
        title: 'less',
        link: '/articleList/fronts_less'
      }, {
        title: 'mongoose',
        link: '/articleList/backstages_mongoose'
      }, {
        title: 'webpack',
        link: '/articleList/tools_webpack'
      }, {
        title: 'gulp',
        link: '/articleList/tools_gulp'
      }, {
        title: 'github',
        link: '/articleList/tools_github'
      }, {
        title: 'photoshop',
        link: '/articleList/tools_photoshop'
      }],
      hotList: [{
        title: '面向对象',
        link: '/articleList/search?q=面向对象'
      }, {
        title: '展示页面',
        link: '/articleList/search?q=页面'
      }, {
        title: '插件封装',
        link: '/articleList/search?q=插件'
      }, {
        title: '游戏',
        link: '/articleList/search?q=游戏'
      }, {
        title: 'web特效',
        link: '/articleList/search?q=特效'
      }, {
        title: '工具',
        link: '/articleList/search?q=工具'
      }, {
        title: '实战项目',
        link: '/articleList/search?q=实战'
      }, {
        title: '数组',
        link: '/articleList/search?q=数组'
      }, {
        title: '对象',
        link: '/articleList/search?q=对象'
      }, {
        title: '字符串',
        link: '/articleList/search?q=字符串'
      }, {
        title: 'promise',
        link: '/articleList/search?q=promise'
      }]
    }
  }
}
