export default {
  data () {
    return {
      langList: [{
        title: 'javascript',
        link: '/'
      }, {
        title: 'es6',
        link: '/'
      }, {
        title: 'html',
        link: '/'
      }, {
        title: 'css',
        link: '/'
      }, {
        title: 'node',
        link: '/'
      }, {
        title: 'vue',
        link: '/'
      }, {
        title: 'react',
        link: '/'
      }, {
        title: 'angular',
        link: '/'
      }, {
        title: 'jquery',
        link: '/'
      }, {
        title: 'require',
        link: '/'
      }, {
        title: 'bootstrip',
        link: '/'
      }, {
        title: 'less',
        link: '/'
      }, {
        title: 'jade',
        link: '/'
      }, {
        title: 'ejs',
        link: '/'
      }, {
        title: 'juicer',
        link: '/'
      }, {
        title: 'webpack',
        link: '/'
      }, {
        title: 'gulp',
        link: '/'
      }, {
        title: 'github',
        link: '/'
      }, {
        title: 'photoshop',
        link: '/'
      }],
      hotList: [{
        title: '面向对象',
        link: '/'
      }, {
        title: '展示页面',
        link: '/'
      }, {
        title: '插件封装',
        link: '/'
      }, {
        title: '游戏',
        link: '/'
      }, {
        title: 'web特效',
        link: '/'
      }, {
        title: '工具',
        link: '/'
      }, {
        title: '实战项目',
        link: '/'
      }, {
        title: '数组',
        link: '/'
      }, {
        title: '对象',
        link: '/'
      }, {
        title: '字符串',
        link: '/'
      }, {
        title: 'promise',
        link: '/'
      }]
    }
  }
}
